### ISSUE TITLE
Any guidance on how one might add vSphere coverage here?

### ISSUE THREAD

**Issue by Analect** [bashofmann/rancher-cluster-templates#1]
I note you have charts for AWS, DO and Equinix. Can you advise if this approach can also cater for deploying an RKE2 cluster to vSphere yet? Thanks.

**Comment by bashofmann** [comment]
Creating a template for vsphere is very similar, you just need to create a vsphere machine/node config instead of a aws/do/equinix one. You can find an example here: https://github.com/rancher/cluster-template-examples/blob/main/charts/templates/nodeconfig-vsphere.yaml.

Alternatively, you can also create a cluster manually through the UI and then have a look at the VmwarevsphereConfig resources created in the local cluster. They are also linked on the cluster detail page under "Related resources".
